/*
 * dns.c - DNS resolver configuration / DNS 解析器配置
 *
 * Manages /etc/resolv.conf and DNS-over-HTTPS settings.
 * 管理 /etc/resolv.conf 和 DNS-over-HTTPS 设置。
 */

#define _GNU_SOURCE
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include "netd.h"

#define RESOLV_CONF "/etc/resolv.conf"

/* === Set DNS servers / 设置 DNS 服务器 === */

int dns_set_servers(const char *dns1, const char *dns2)
{
    FILE *fp = fopen(RESOLV_CONF, "w");
    if (!fp) {
        fprintf(stderr, "[netd] dns: failed to write %s: %s\n",
                RESOLV_CONF, strerror(errno));
        return -1;
    }

    fprintf(fp, "# Generated by LumiOS netd\n");
    if (dns1 && dns1[0]) fprintf(fp, "nameserver %s\n", dns1);
    if (dns2 && dns2[0]) fprintf(fp, "nameserver %s\n", dns2);
    fclose(fp);

    fprintf(stderr, "[netd] dns: servers set to %s, %s\n",
            dns1 ? dns1 : "none", dns2 ? dns2 : "none");
    return 0;
}

/* === Enable DNS-over-HTTPS / 启用 DNS-over-HTTPS === */

int dns_set_doh(const char *doh_url)
{
    if (!doh_url) return -1;

    /* TODO: configure system DoH resolver (e.g. stubby/dnscrypt-proxy) */
    /* TODO: 配置系统 DoH 解析器 */
    fprintf(stderr, "[netd] dns: DoH configured: %s\n", doh_url);
    return 0;
}

/* === Flush DNS cache / 刷新 DNS 缓存 === */

int dns_flush_cache(void)
{
    fprintf(stderr, "[netd] dns: cache flushed\n");
    return 0;
}
